name: Client CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      
      - name: Install dependencies
        run: |
          cd ./client
          npm ci
      
      - name: Run ESLint
        run: |
          cd ./client
          npm run lint
      
      - name: Run Tests
        run: |
          cd ./client
          npm run test
      
      - name: Build React App
        run: |
          cd ./client
          npm run build